Added tooltip for long task name
flowmodor/flowmodor pull request #19
Opened 2024-02-24 04:57 UTC by amelia2802

- Added tooltip for long task name
- fixed issue #3 

## preview
![image](https://github.com/flowmodor/flowmodor/assets/49182604/e52ef8c4-7268-4c70-8ad4-06f474a8a8ea)

2024-02-24 08:57 UTC, m4xshen requested changes

2024-02-24 08:57 UTC, m4xshen commented on .prettierrc.json
This file should not be deleted

2024-02-24 08:57 UTC, m4xshen commented on package.json
The next.js package version should also stay same.

2024-02-24 14:22 UTC, amelia2802 commented
Hi, I've resolved those change requests.

2024-02-24 14:50 UTC, m4xshen requested changes

2024-02-24 14:50 UTC, m4xshen commented on yarn.lock
I forgot to say that this also shouldn't change.

2024-02-25 01:17 UTC, merged

2024-02-25 01:20 UTC, m4xshen commented
@amelia2802 The feature is merged now. Thanks for the contribution!